### ISSUE TITLE
cannot start sonic builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#10]
- Cannot start sonic builder.

![ff](https://user-images.githubusercontent.com/21218053/64349540-7054fb00-cff7-11e9-8b99-e1733fb96681.png)

#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by ahsayde** [comment]
Can't reproduce 
@Dina-Abd-Elrahman can you check again

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fine now, we can close the issue. 

##### Branch: `development`
##### Commit_ID: f17fc1e495049a3706e3d3dbfb39d2de5b1ba237
