### ISSUE TITLE
cannot start threebot builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#11]
error while trying to start threebot builder 

![ff](https://user-images.githubusercontent.com/21218053/64351290-55d05100-cffa-11e9-951b-145fa2a04706.png)

#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by xmonader** [comment]
can't be the case anymore.
