### ISSUE TITLE
cannot build zerohub builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#14]
error while trying to build zerohub builder 

![ff](https://user-images.githubusercontent.com/21218053/64354340-8e265e00-cfff-11e9-9240-59f302668805.png)

#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by Dina-Abd-Elrahman** [comment]
- this error is solved now after this commit: 8f21263e422cbb10a9f3e1f8c4f5342b5b50092f 

but there is a new error now, 

![ff](https://user-images.githubusercontent.com/21218053/64530643-f29e3180-d30d-11e9-8f17-1c6b829167dc.png)

**Comment by ahsayde** [comment]
fixed by this commit
99cc3908ae80410c5e25f7700d4e37ff13189f6f

**Comment by Dina-Abd-Elrahman** [comment]
- working fine now
