### ISSUE TITLE
cannot install zdisk buidler

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#17]
- cannot install `zdisk` builder

![ff](https://user-images.githubusercontent.com/21218053/64781754-e7dcda00-d563-11e9-8adc-d4fcc7ef12af.png)

**Comment by zaibon** [comment]
you can delete this builder completely, Zdisk is a project that has been discontinued more then a year ago.

**Comment by rkhamis** [comment]
removed
