### ISSUE TITLE
Builders: AtomicSwap

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#18]
- is it still needed or used somewhere?
- doesn't follow builders guidlines

**Comment by rkhamis** [comment]
Needed, yes

**Comment by rkhamis** [comment]
probably can be cleaned up

**Comment by rkhamis** [comment]
mark as unused or remove

**Comment by ahsayde** [comment]
blockchain builders and tests moved to archived directory to be removed

**Comment by Pishoy** [comment]
verified 

```
https://github.com/threefoldtech/jumpscaleX_builders/tree/unstable/archived/blockchain
```
