### ISSUE TITLE
why we have j__builders in all builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#28]
- we have `j__builders` in all groups in builders like this:

![ff](https://user-images.githubusercontent.com/21218053/64952059-9db76980-d87f-11e9-885f-8deb836bcddc.png)

![ff_2](https://user-images.githubusercontent.com/21218053/64952068-a1e38700-d87f-11e9-8b18-6f76900d686c.png)

**Comment by xmonader** [comment]
that's a reference for builders JSGroup.
