### ISSUE TITLE
DigitalMe builder error

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#3]
- cannot build digitalme builder

![ff](https://user-images.githubusercontent.com/21218053/64338941-25c98380-cfe3-11e9-95e0-decf7d669b55.png)

**Comment by Dina-Abd-Elrahman** [comment]
the issue is related to this one 

https://github.com/threefoldtech/jumpscaleX_builders/issues/4

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by rkhamis** [comment]
Perhaps we can also rename to ThreebotBuilder

**Comment by ashraffouda** [comment]
it is not used, removed it
