### ISSUE TITLE
create jumpscale builder for taiga 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_builders#33]
taiga is a project management tool which installed [here](http://167.71.6.185) using installation docs [here](https://taigaio.github.io/taiga-doc/dist/setup-production.html)

- create jumpscale builder deploy script [deploy.py](deploy.py) which installs & configures

more deatils here https://support.grid.tf/thread/49

**Comment by ranatrk** [comment]
The builder is already implemented in `j.builders.apps.taiga`, but there are some errors when installing. 
Currently working on making sure it is working correctly

**Comment by ranatrk** [comment]
WIP: some refactoring in install and start functions is done. Need to fix some configurations for the builder to be complete and ready to be used in a script.

**Comment by ranatrk** [comment]
Fixes in builder: https://github.com/threefoldtech/jumpscaleX_builders/commit/a5aaca1e6b64d553667637ab265a7222dc57fd70

configurations will be altered slightly in the script, but still working on changing the default password for admin user

**Comment by ranatrk** [comment]
- Created taiga server to start taiga with certain configs
- Added installation and starting of events 

**Builder**:https://github.com/threefoldtech/jumpscaleX_builders/commit/cacc48a73d28bacc8494ee5c07abf3b9b8fa1bcd
**Server**: https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/a71b15a106f60c4297a3db10e750784b3e9fc0db



**_note_** To use the server : 
```
taiga_server = j.servers.taiga.get(backend_repo="",frontend_repo="",events_repo="")
taiga_server.install()
taiga_server.start()
```

**Comment by ranatrk** [comment]
Some changes were done to taiga builder and server.  Now working
Builder: https://github.com/threefoldtech/jumpscaleX_builders/blob/development/JumpscaleBuilders/apps/BuilderTaiga.py
Server : https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/development/JumpscaleLibsExtra/servers/taiga/TaigaServer.py

To use the server:
```
taiga_server = j.servers.taiga.get(backend_repo="",
                                   frontend_repo="",
                                   events_repo="",
                                   host="",port="",
                                   branch_backend="",
                                   branch_frontend="",
                                   branch_events="",
                                   secret_="")
taiga_server.install(reset=True)
taiga_server.start()
```

**Comment by hossnys** [comment]
verified  :
```
JSX> taiga_server = j.servers.taiga.get(backend_repo="https://gitlab.com/threefoldforks/Threefold-Circles.git",frontend_repo="http
s://gitlab.com/threefoldforks/Threefold-Circles-front-dist.git",events_repo="https://gitlab.com/threefoldforks/Threefold-Circ
les-events.git",branch_backend="stable",branch_frontend="stable",branch_events="master")                                     

JSX> taiga_server.install()
JSX> taiga_server.start() 
```
![Screenshot from 2019-10-16 11-50-33](https://user-images.githubusercontent.com/26298009/66908105-d0818880-f00a-11e9-84ca-aec447d34769.png)
