### ISSUE TITLE
Make sure to install rabbitmq for taiga

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#35]
Make sure to install rabbitmq (create a builder for it if needed) + start it + configured for taiga builder https://taigaio.github.io/taiga-doc/dist/setup-production.html

**Comment by ranatrk** [comment]
Added:
- start rabbitmq service
- rabbitmq user
- clean function to delete users, directories installed

**Comment by siddiquagig** [comment]
Got this error when doing ```j.servers.taiga.default.install(reset=True)```

and so cannot start taiga


![image](https://user-images.githubusercontent.com/25789724/67853763-9e067e00-fb28-11e9-919e-563231590fa6.png)

**Comment by hossnys** [comment]
@siddiquagig  i think you didn't start the server yet you did install only , you can follow steps [here](https://docs.grid.tf/threefold/itenv_web_v2/src/branch/master/projectmgmt/taiga.md)
and try to use Taiga builder also .

**Comment by siddiquagig** [comment]
@hossnys , the error comes while installing taiga , i have told Rana this and she was checking

**Comment by ranatrk** [comment]
The following fixed the issue : https://github.com/threefoldtech/jumpscaleX_builders/commit/9f03239a121dc7a6fe2e93f2fb6cc981cc342c4d

**Comment by siddiquagig** [comment]
Verified

Install and start Taiga:

```
j.servers.taiga.default
j.servers.taiga.default.host = "CONTAINER_IP"
j.servers.taiga.default.install(reset=True)
j.servers.taiga.default.start()
```

Then check Rabbitmq:


![image](https://user-images.githubusercontent.com/25789724/68669819-ea0fe480-0564-11ea-959a-cf421dce5697.png)
