### ISSUE TITLE
cgit builder

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#36]
- https://git.zx2c4.com/cgit/tree/README
- prepare configurations to use nginx instead of apache

**Comment by Pishoy** [comment]
builder is ready and service are started but when i add a repo in cgit directory does not shown in web, will check ..

**Comment by Pishoy** [comment]
builder ready https://github.com/threefoldtech/jumpscaleX_builders/commit/c1e39c0d2dd9f5d201ff17b86f15cef7e35915b6

**Comment by Dina-Abd-Elrahman** [comment]
- start method in cgit builder raises this error 
![error](https://user-images.githubusercontent.com/21218053/70139831-06063200-169c-11ea-8e41-3c7fe5fc1399.png)

**Branch**
development

**Commit_ID**
6ae027eb95ddc8e2361cb85dce64314431b27561

**Comment by Dina-Abd-Elrahman** [comment]
- it's working now correctly.
