### ISSUE TITLE
cmake builder error

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#4]
cannot build cmake builder 

![ff](https://user-images.githubusercontent.com/21218053/64339062-7214c380-cfe3-11e9-9bc1-820b13fb9837.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by alichaddad** [comment]
Fixed here ed19c65be0f08f0f0bcee2d495d06332362107c3 and 62bf4e6eb86b754a1f4eaf299104fb96cc8ec588

**Comment by Dina-Abd-Elrahman** [comment]
- verified, 

#### Branch: `development`
#### Commit_ID: ca5c7bada842dcf309dfdd3a58d7443d1efdd46c
