### ISSUE TITLE
Issue with ZDB builder when starting Threebot Server

### ISSUE THREAD

**Issue by abdulgig** [threefoldtech/jumpscaleX_builders#42]
With new JSX install, zdb fails to compile when starting the Threebot server, 

        + git clone https://github.com/threefoldtech/0-db.git --branch development
        Cloning into '0-db'...
        + cd /tmp/jumpscale/zdb/0-db
        + make
        namespace-editor.c: In function ‘namespace_edit’:
        namespace-editor.c:54:5: error: unknown type name ‘ns_header_t’; did you mean ‘index_header_t’?
             ns_header_t header;
             ^~~~~~~~~~~
             index_header_t
        namespace-editor.c:64:11: error: request for member ‘namelength’ in something not a structure or union
             header.namelength = strlen(namespace->name);
                   ^
        namespace-editor.c:65:11: error: request for member ‘passlength’ in something not a structure or union
             header.passlength = namespace->password ? strlen(namespace->password) : 0;
                   ^
        namespace-editor.c:66:11: error: request for member ‘maxsize’ in something not a structure or union
             header.maxsize = namespace->maxsize;
                   ^
        namespace-editor.c:67:11: error: request for member ‘flags’ in something not a structure or union
             header.flags = namespace->public ? NS_FLAGS_PUBLIC : 0;
                   ^
        namespace-editor.c:69:34: error: ‘ns_header_t’ undeclared (first use in this function); did you mean
        ‘index_header_t’?
             if(write(fd, &header, sizeof(ns_header_t)) != sizeof(ns_header_t))
                                          ^~~~~~~~~~~
                                          index_header_t
        namespace-editor.c:69:34: note: each undeclared identifier is reported only once for each function it appears in
        make[2]: *** [namespace-editor.o] Error 1
        make[1]: *** [all] Error 2
        make: *** [all] Error 2

```

JumpScale Builder

commit 85b4d7de9a604b52cd384066be8937f939cc4cfa (HEAD -> development, origin/development)
Merge: d445204 bc919ec
Author: Waleed <waleed.hammam@gmail.com>
Date:   Thu Dec 5 14:40:24 2019 +0200

    Merge pull request #41 from threefoldtech/develop_tcprouter_fix

    use go mudules to build tcp router

**Comment by zaibon** [comment]
0-db build as been fixed in https://github.com/threefoldtech/0-db/commit/02d205f8164c99839c33932e5bb4d5089d366286
