### ISSUE TITLE
cannot build freeflow builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#5]
error while trying to build freeflowpages builders

![ff](https://user-images.githubusercontent.com/21218053/64339216-d3d52d80-cfe3-11e9-95c7-d3fc32ff5cba.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by alichaddad** [comment]
Fixed in c2906e8c2ba145424b8dbd788b95e5fea7db9907

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
