### ISSUE TITLE
restic/rest-server to be included in restic builder

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#51]
Build and install `rest-server` as part of the restic builder.

To verify, run `j.builders.storage.restic.install(reset=True) `, after it finishes successfully, you should find `restic` and `rest-server` under `/sandbox/bin/`

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_builders/commit/5b4b8f4b882ed68f99f5ca8b6b5469ebdb1f1abe

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
