### ISSUE TITLE
create a builder for codeserver [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#55]
Create a builder for https://github.com/cdr/code-server 

Note:
- use binary release

**Comment by m-motawea** [comment]
**commit** :https://github.com/threefoldtech/jumpscaleX_builders/commit/3773154250883683e07abcf09e140ae26b89e96c

**Changelog**

- Added builder for code-server 

- These is the used version, in case of update just change it in builder init

```python
 self.RELEASE_VERSION = "2.1698"
 self.TAR_VERSION = "2.1698-vsc1.41.1"
```

**Comment by hossnys** [comment]
branch unstable :
steps: 
```
j.builders.apps.codeserver.build()  
j.builders.apps.codeserver.install() 
j.builders.apps.codeserver.start() 

```
![Screenshot from 2020-02-18 10-57-49](https://user-images.githubusercontent.com/26298009/74721854-b0740700-5240-11ea-9fbf-233d4cc7ade5.png)


but when uninstall it just clean the binary and packages of code-server without stopping the service itself , so the server is still running .

![Screenshot from 2020-02-18 11-31-07](https://user-images.githubusercontent.com/26298009/74722667-fc737b80-5241-11ea-8af1-2e854449858b.png)

so need to call stop() in the uninstall method .

**Comment by m-motawea** [comment]
*commit* https://github.com/threefoldtech/jumpscaleX_builders/commit/c83515280de8b27e230b32a3899bc607c65e53b5

Summary:
* check for server process state in ```uninstall()``` and stop it if running.
* move binary deletion from ```clean()``` to ```uninstall()``` and ```reset()```.

**Comment by hossnys** [comment]
verified on branch unstable 

![Screenshot from 2020-02-18 16-54-10](https://user-images.githubusercontent.com/26298009/74747304-69e9d100-526f-11ea-8df9-5ca5ef96e00e.png)
