### ISSUE TITLE
update syncthing and verify it's working [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#58]
- make sure to revisit the builder for syncthing
- make sure it works correctly

**Comment by Hamdy** [comment]
Syncthing is working, However I had to upgrade golang ot version 1.14 rather than 1.12.x

**Comment by Hamdy** [comment]
Also another issue I encountered, was when running as a root , it gives warning, then stops 
first time then run correctly again, so I updated builder to add new user called `syncthing` and ran the server from that user

Another issue, is it can not run in tmux in proper way sincce tmux uses something like
`exec -a startupcmd_{cmd} cmd {args}` which does not work with syncthing that assumes that the first argument number 0 passed to it is the same exact name as the binary name so `startupcmd_syncthing` now passed as (0) argument by exec will not work, so I renamed the binary to startupcmd_syncthing which is a workaround, not the best thing, but I don't think we have many of usecases like this any way!  

here's the commit : https://github.com/threefoldtech/jumpscaleX_builders/commit/68c3df301baea7a0aefdd2acc577782763abde27

**Comment by Hamdy** [comment]
**To verify** : `j.builders.storage.syncthing.test`

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
