### ISSUE TITLE
cannot build gitea builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#6]
error while trying to build gitea builder 

![ff](https://user-images.githubusercontent.com/21218053/64341129-ff5a1700-cfe7-11e9-9277-4b6f98731131.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by ahsayde** [comment]
can't reproduce

**Comment by Dina-Abd-Elrahman** [comment]
- working fine now.
