### ISSUE TITLE
cannot build graphql builder 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#7]
error while trying to build graphql builder

![ff](https://user-images.githubusercontent.com/21218053/64341267-47793980-cfe8-11e9-9f35-773b62a3ff60.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by ranatrk** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX_builders/commit/8f21263e422cbb10a9f3e1f8c4f5342b5b50092f

**Comment by Dina-Abd-Elrahman** [comment]
this error is fixed now, but I'm facing new error now. 

![ff](https://user-images.githubusercontent.com/21218053/64680373-f5b82f80-d47d-11e9-8e31-9f6666b54523.png)

**Comment by ranatrk** [comment]
Fixes : 
changed the destination where [graphql_websockets](https://github.com/threefoldfoundation/graphql_websockets) is cloned and used for install
https://github.com/threefoldtech/jumpscaleX_builders/commit/065c69c19ba1a59a619cc7c95ca143e78ab75d71

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit ID: 065c69c19ba1a59a619cc7c95ca143e78ab75d71

it works fine now.
