### ISSUE TITLE
error in odoo builder

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_builders#8]
cannot build odd builder 

![ff](https://user-images.githubusercontent.com/21218053/64342283-74c6e700-cfea-11e9-9a6b-1598654b46d6.png)

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID:  23d753f738abbc7add99b98b6c23619ab20671d2

**Comment by ranatrk** [comment]
Fix done in https://github.com/threefoldtech/jumpscaleX_builders/commit/466cc8daba55155698861486f642e79f48736c09

**Comment by Dina-Abd-Elrahman** [comment]
#### Branch: `development`
#### Commit_ID: 065c69c19ba1a59a619cc7c95ca143e78ab75d71

- it's working now
